
name: Analyse
on:
  push:
    branches:
      - master # or the name of your main branch
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - run: pwd
      - run: ls -la .
      - run: npm i -g pnpm
      - run: pnpm i
      - run: pwd
      - run: ls .
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.1.0
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: /app/
      - run: ls -la .